### PR TITLE
Move the os-images and os-engine buildfiles into this repo

### PR DESCRIPTION
**Pull request by SvenDowideit**
Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>

when we merge this we should update the 'os-images' repo with a note saying its deprecated.

this PR also imports the contents of the `os-engines repo` - which should be deprecated/mothballed.

note that atm, this PR is paired with https://github.com/rancher/os-images/pull/114 and the result is that we have 2 sets of places where we define images - the os repo, and this one. Now that i've done it, I'm thinking that it may be better to move the `images` dir from the `os` repo here too..

### CODE REVIEW

**Comment by SvenDowideit** [comment]
needs update we've merged some PRs

**Comment by SvenDowideit** [comment]
don't merge yet - I found a problem with the engine tags i need to fix.

but please review anyway :)

**Comment by SvenDowideit** [comment]
ok, engine tags fixes, and 1.12.3 arm images added

**Comment by joshwget** [comment]
What do we do about images that don't have a service definition? os-base is the only one to come to mind, but I'm not sure how that'd be integrated here.

**Comment by SvenDowideit** [comment]
I'd like all images to eventually get service definitions - but yup, dunno yet

**Pull request merged**
