### PR TITLE
Update zfs to 0.7.12

### PR DESCRIPTION
**Pull request by zimme**

### CODE REVIEW

**Comment by zimme** [comment]
Would it make more sense to change the versioning of the zfs service to follow zfs versions instead?

`<zfs_version>` for the normal case and
`<zfs_version>_<build_number>` in cases where we've done changes to the service code but not changed the zfs version.

This way we could have different versions of the zfs service available and whenever a new version of zfs is released we can just build a new service version based on that and people can upgrade without having to rebuild the zfs service container with the new zfs version or wait until the next rancher os release.

**Comment by niusmallnan** [comment]
You want something like this?
```
$ ros s list | grep zfs
zfs-0.7.12
zfs-0.7.9
zfs-0.7.8
...
```

**Comment by zimme** [comment]
Yes, that is what I'm thinking.

**Comment by zimme** [comment]
or if it's possible to choose the version for the zfs service in some other way

**Comment by zimme** [comment]
Today you can only choose the zfs service from an erlier version of rancher, but not choose based on the zfs version

**Pull request merged**
