### PR TITLE
Add open-iscsi support

### PR DESCRIPTION
**Pull request by SvenDowideit**
Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>

It installs, but I haven't set up an iSCSI target and tested that yet.

testing with https://wiki.archlinux.org/index.php/TGT_iSCSI_Target

### CODE REVIEW

**Comment by SvenDowideit** [comment]
on my ubuntu box - which i'm using to create targets
```
tgtadm --lld iscsi --op new --mode target --tid 2 -T 10.10.10.4:vol1
root@i7:/home/sven# iscsiadm -m discovery -t sendtargets -p 10.10.10.4
10.10.10.4:3260,1 iqn.2001-04.com.example:storage.disk2.amiens.sys1.xyz
root@i7:/home/sven# dd if=/dev/zero of=/data/iscsi/vol1.dd bs=1M count=10
10+0 records in
10+0 records out
10485760 bytes (10 MB) copied, 0.0178403 s, 588 MB/s
root@i7:/home/sven# tgtadm --lld iscsi --op new --mode logicalunit --tid 1 --lun 1 -b /data/iscsi/vol1.dd
tgtadm: this logical unit number already exists
root@i7:/home/sven# tgtadm --lld iscsi --op new --mode logicalunit --tid 2 --lun 1 -b /data/iscsi/vol1.dd
root@i7:/home/sven# tgtadm --lld iscsi --op bind --mode target --tid 2 -I ALL
root@i7:/home/sven#
root@i7:/home/sven# iscsiadm -m discovery -t sendtargets -p 10.10.10.4
10.10.10.4:3260,1 iqn.2001-04.com.example:storage.disk2.amiens.sys1.xyz
10.10.10.4:3260,1 10.10.10.4:vol1
```
and then on a RancherOS vm running in my network:
```
sven-machine:~$ sudo bash
sven-machine:/home/rancher# ros service enable
> DEBU[0000] Warning: user-data hostname (sven-machine) overrides metadata hostname (sven-machine)

sven-machine:/home/rancher#
sven-machine:/home/rancher# ros service enable  https://raw.githubusercontent.com/SvenDowideit/os-services/96abe71764425b96e2fbef31a222f80d1fb6370c/i/iscsi.yml
> DEBU[0000] Warning: user-data hostname (sven-machine) overrides metadata hostname (sven-machine)

> DEBU[0000] Using cached file: /var/lib/rancher/cache/7f5e6bc1d80b92f6c01f6e705b958c33
> DEBU[0000] Warning: user-data hostname (sven-machine) overrides metadata hostname (sven-machine)

> DEBU[0000] Loaded https://raw.githubusercontent.com/SvenDowideit/os-services/96abe71764425b96e2fbef31a222f80d1fb6370c/i/iscsi.yml from https://raw.githubusercontent.com/SvenDowideit/os-services/96abe71764425b96e2fbef31a222f80d1fb6370c/i/iscsi.yml
Pulling open-iscsi (rancher/os-iscsi:latest)...
latest: Pulling from rancher/os-iscsi
aafe6b5e13de: Already exists
0a2b43a72660: Already exists
18bdd1e546d2: Already exists
8198342c3e05: Already exists
f56970a44fd4: Already exists
b7445b2fc625: Already exists
747cc9ccbda8: Already exists
1bb913bbd28a: Already exists
6a4730fcad63: Already exists
8dab5f70a265: Already exists
39422d9443c2: Pull complete
Digest: sha256:83f2b04ffb188e8b8e9a59491567f2ce122209923185e61b51cb88dd02d8a3cb
Status: Downloaded newer image for rancher/os-iscsi:latest
sven-machine:/home/rancher# ros service up open-iscsi
> DEBU[0000] Warning: user-data hostname (sven-machine) overrides metadata hostname (sven-machine)

> DEBU[0000] Warning: user-data hostname (sven-machine) overrides metadata hostname (sven-machine)

> DEBU[0000] Using cached file: /var/lib/rancher/cache/581830721ada1344f5906abc4d70e565
> DEBU[0000] Loaded kernel-headers-system-docker from https://raw.githubusercontent.com/rancher/os-services/v1.0.1/k/kernel-headers-system-docker.yml
> DEBU[0000] Using /proc/version to set rancher.environment.KERNEL_VERSION = 4.9.24-rancher
> DEBU[0000] Using /proc/version to set rancher.environment.KERNEL_VERSION = 4.9.24-rancher
> DEBU[0000] Using cached file: /var/lib/rancher/cache/3629dedb2f3f678be8bdeb03131447c6
> DEBU[0000] Loaded https://raw.githubusercontent.com/SvenDowideit/os-services/96abe71764425b96e2fbef31a222f80d1fb6370c/i/iscsi.yml from https://raw.githubusercontent.com/SvenDowideit/os-services/96abe71764425b96e2fbef31a222f80d1fb6370c/i/iscsi.yml
> DEBU[0000] Using cached file: /var/lib/rancher/cache/a45f7972636e05f6096d11cc5bf79f31
> DEBU[0000] Loaded https://raw.githubusercontent.com/SvenDowideit/os-services/iscsi/i/iscsi.yml from https://raw.githubusercontent.com/SvenDowideit/os-services/iscsi/i/iscsi.yml
> INFO[0000] Project [os]: Starting project
> DEBU[0000] Using /proc/version to set rancher.environment.KERNEL_VERSION = 4.9.24-rancher
> DEBU[0000] Using /proc/version to set rancher.environment.KERNEL_VERSION = 4.9.24-rancher
> DEBU[0000] Using /proc/version to set rancher.environment.KERNEL_VERSION = 4.9.24-rancher
> DEBU[0000] Using /proc/version to set rancher.environment.KERNEL_VERSION = 4.9.24-rancher
> DEBU[0000] Using /proc/version to set rancher.environment.KERNEL_VERSION = 4.9.24-rancher
> DEBU[0000] Using /proc/version to set rancher.environment.KERNEL_VERSION = 4.9.24-rancher
> DEBU[0000] Using /proc/version to set rancher.environment.KERNEL_VERSION = 4.9.24-rancher
> DEBU[0000] Using /proc/version to set rancher.environment.KERNEL_VERSION = 4.9.24-rancher
> DEBU[0000] Using /proc/version to set rancher.environment.KERNEL_VERSION = 4.9.24-rancher
> INFO[0000] [0/18] [open-iscsi]: Starting
> INFO[0000] Recreating open-iscsi
> DEBU[0000] Warning: user-data hostname (sven-machine) overrides metadata hostname (sven-machine)

> DEBU[0000] Rebuild values                                newRebuildLabel= origRebuildLabel= outOfSync=false rebuildLabelChanged=false


> INFO[0009] [1/18] [open-iscsi]: Started
> INFO[0009] Project [os]: Project started
sven-machine:/home/rancher#
[root@rancher-dev rancher]# iscsiadm -m discovery -t st -p 10.10.10.4
10.10.10.4:3260,1 iqn.2001-04.com.example:storage.disk2.amiens.sys1.xyz
10.10.10.4:3260,1 10.10.10.4:vol1
[root@rancher-dev rancher]# iscsiadm --mode node --targetname 10.10.10.4:vol1 --portal 10.10.10.4:3260 --login
Logging in to [iface: default, target: 10.10.10.4:vol1, portal: 10.10.10.4,3260] (multiple)
Login to [iface: default, target: 10.10.10.4:vol1, portal: 10.10.10.4,3260] successful.
[root@rancher-dev rancher]# iscsiadm -m node -L all
iscsiadm: default: 1 session requested, but 1 already present.
iscsiadm: Could not log into all portals
Logging in to [iface: default, target: iqn.2001-04.com.example:storage.disk2.amiens.sys1.xyz, portal: 10.10.10.4,3260] (multiple)
Login to [iface: default, target: iqn.2001-04.com.example:storage.disk2.amiens.sys1.xyz, portal: 10.10.10.4,3260] successful.
```

**Comment by swapnil-pandey** [comment]
`iscsiadm -m discovery -t st -p 10.10.10.4`
What is the IP mentioned here?

**Comment by lfdominguez** [comment]
My problem:
screenshot_20180911_131819

**Comment by swapnil-pandey** [comment]
@Ifdominguez can you check if the iscsi service is running or not.

**Comment by lfdominguez** [comment]
screenshot_20180911_132203

**Comment by swapnil-pandey** [comment]
I got iscsi running by installing it inside the kubelet contain er rather than on the host itself.

**Comment by lfdominguez** [comment]
I think that the problem here is that the service not see the host `/etc` folder, how i can add this folder to the open-iscsi ros service????

**Pull request merged**
