### PR TITLE
Add a kernel-headers alias to install the running kernel-headers version

### PR DESCRIPTION
**Pull request by SvenDowideit**
Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>

now to decide where to set that env var.

### CODE REVIEW

**Comment by joshwget** [comment]
Very minor thing. Can we switch to `KERNEL_VERSION`? Most of the other environment variables for our services are underscore separated.

**Comment by joshwget** [comment]
You could add it dynamically in the [environment lookup code](https://github.com/rancher/os/blob/master/docker/env.go#L47).

**Comment by SvenDowideit** [comment]
@joshwget nice - thanks!

**Comment by joshwget** [comment]
LGTM

**Pull request merged**
