### PR TITLE
Added rancher server as a service

### PR DESCRIPTION
**Pull request by deniseschannon**
@ibuildthecloud: This won't work until os: v0.3.1 is released due to the port mapping not working in os: v0.3.0.

### CODE REVIEW

**Comment by deniseschannon** [comment]
@ibuildthecloud only issue with rancher server is anytime we reboot, the container is restarted as well and nothing is saved.

It also appears that once you enable a service and if it had the `latest` tag, we don't have an option to update the image if `latest` is updated. 

Maybe we need to have some kind of upgrade functionality for service so that someone could use a latest tag and update the image?

**Comment by ibuildthecloud** [comment]
You need to create a data volume container and set the label "io.rancher.os.remove=false".  Then do `volumes-from` from the data container.  So something like...

```yaml
rancher-state:
  image: busybox
  command: true
  volumes:
  - /var/lib/cattle
  - /var/lib/mysql

rancher:
  ..stuff..
  volumes-from:
  - rancher-state
```

**Comment by imikushin** [comment]
Here's what I've found: if `--restart=always` is set on a container, the container survives reboots. So, the cure is to fix rancherio/os#230

**Comment by imikushin** [comment]
@deniseschannon please add `restart: always` to `rancherserver` container

**Comment by imikushin** [comment]
Also, `rancher/server` has some initial data in `/var/lib/mysql`, so if that dir is empty, the container would appear to be running, while in fact its internal init script would be just logging crap every second. So the correct data container should look like this:
```yml
rancher-state:
  image: rancher/server:latest
  labels:
  - io.rancher.os.createonly=true
  - io.rancher.os.remove=false
  volumes:
  - /var/lib/cattle
  - /var/lib/mysql
```
Somewhat weird, because it's the same image. 

Anyway, this doesn't work yet: rancherio/os#275

**Comment by cloudnautique** [comment]
If you bind mount in /var/lib/MySQL it gets a blank initial data directory. I need to change the init script to re initialize the directory. Alternatively, you can do volumes from another rancher server container.

**Comment by imikushin** [comment]
@cloudnautique now I know :)

**Comment by imikushin** [comment]
So this is perfectly working and persisting state:
```yml
rancherserver:
  image: rancher/server:latest
  restart: always
  labels:
  - io.rancher.os.remove=false
  volumes_from:
  - rancher-state
  ports:
  - 8080:8080
```
if, of course, rancherio/os#277 is merged ;)

**Comment by imikushin** [comment]
@ibuildthecloud So, now (as of os-v0.3.1-rc1) `io.rancher.os.remove=false` is broken: `rancherserver` and `rancherstate` from previous boot become `rancherserver-f6f2b405cbb3ddcaebe1d3d21dc4d28c12182276` and `rancher-state-509585100fb8965b8e0300c47da08bc62e87f2e6` on the next boot and don't go anywhere, just stay exited.

**Comment by ibuildthecloud** [comment]
I believe this is because in 0.3.1 we broke labels.  If you do a config export --full they are just a long array of numbers.  We did some changes to support both a map or slice as the labels param and that seems to have broken it.

**Comment by ibuildthecloud** [comment]
I just noticed this behavior yesterday and haven't dug into the details yet.

**Comment by deniseschannon** [comment]
I'll take a look into it later today.

**Comment by deniseschannon** [comment]
The docker inspect on labels for the containers still show the labels correctly, so I'm not sure how the labels are converted to the config file. started a new issue to track the labels issue. https://github.com/rancherio/os/issues/281

**Comment by deniseschannon** [comment]
I fixed the labels so that instead of the array of numbers, it's showing the actual labels. It was only a Marshaling change. Unfortunately, the labels issue of `io.rancher.os.remove=false` is still broken. I'll open a new issue and keep trying to investigate.

**Comment by deniseschannon** [comment]
I've created a PR to fix the labels issue with `io.rancher.os.remove=false`. https://github.com/rancherio/os/pull/297

Upon my numerous tests, I've found some interesting behavior.

Strange Behavior 1: If at a later time, we want to disable the service, we are unable to using 'service disable' due to the label and restart policy. Filed under https://github.com/rancherio/os/issues/299

Strange Behavior 2: If we put rancher server into a system-service using `io.rancher.os.scope=system`, then we'd need to add in 
```
links:
  - network
```
https://github.com/rancherio/os/issues/304

**Pull request closed without merging**
