### PR TITLE
add Rancher-server as a dev test service

### PR DESCRIPTION
**Pull request by SvenDowideit**
Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>

### CODE REVIEW

**Comment by SvenDowideit** [comment]
@ibuildthecloud  I've made both the dev and stable service as they're called out in the quickstart 

http://docs.rancher.com/rancher/v1.3/en/quick-start-guide/

**Comment by joshwget** [comment]
You can use interpolation to make the tag customizable https://github.com/rancher/os-services/blob/master/a/amazon-ecs-agent.yml#L2.

`rancher/server:latest` shouldn't really be called `rancher-server-dev`. It's what most people use for production.

**Comment by SvenDowideit** [comment]
from the docs:

```
rancher/server:latest tag will be our latest development builds. These builds will have been validated through our CI automation framework. These releases are not meant for deployment in production.
rancher/server:stable tag will be our latest stable release builds. This tag is the version that we recommend for production.
```

**Comment by ibuildthecloud** [comment]
LGTM

**Pull request merged**
