### PR TITLE
Properly delegate quoted parameters to zfs-tools

### PR DESCRIPTION
**Pull request by chrisseto**

### CODE REVIEW

**Comment by niusmallnan** [comment]
Hi, thanks for your PR.
Is there something that blocked you? Could you please give me more steps?

**Comment by chrisseto** [comment]
Ah, yes sorry.

Using `$@` without quotes don't properly pass quoted parameters to the zfs-tools container. So any arguments (zpools or zfs filesystems) with a space in the name are effectively inaccessible.

I was attempting to snapshot a dataset but kept getting `too many arguments` errors from the tools.

`zfs snapshot '/my/data set@today'` gets run as `zfs snapshot /my/data set@today` without this fix.

**Comment by niusmallnan** [comment]
@Jason-ZW Please help review.

**Comment by Jason-ZW** [comment]
LGTM

**Pull request merged**
